-- =====================================================
-- Schema D1 (SQLite) — Route 66 / MenuWebAR
-- =====================================================
-- Traduccion 1:1 del esquema Postgres (supabase-schema.sql) a SQLite/D1.
-- Diferencias resueltas vs Postgres:
--   - int4 generated by default as identity  -> INTEGER PRIMARY KEY AUTOINCREMENT
--   - text[] (ingredientes)                  -> TEXT que guarda un JSON array ("[]")
--   - timestamptz                            -> TEXT con fecha ISO 8601
--   - boolean                                -> INTEGER 0/1
--   - now()                                  -> el adaptador inserta new Date().toISOString()
--   - constraint ~ regex (hex color)         -> se valida en el adaptador (SQLite no
--                                               trae regex sin extension)
--   - FK ON DELETE CASCADE / SET NULL        -> declaradas; requieren PRAGMA foreign_keys=ON
--                                               (el adaptador lo activa por conexion)
--
-- Aplicar:
--   Local:      wrangler d1 execute menuwebar-db --local  --file=server/src/data/d1-schema.sql
--   Produccion: wrangler d1 execute menuwebar-db --remote --file=server/src/data/d1-schema.sql

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS categorias (
    id_categ     INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre_categ TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS imagenes (
    id_image     INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre_image TEXT NOT NULL,
    url_image    TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS modelos (
    id_model     INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre_model TEXT NOT NULL,
    url_model    TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS platos (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre           TEXT NOT NULL,
    descripcion      TEXT NOT NULL DEFAULT '',
    precio           INTEGER NOT NULL,
    categoria        INTEGER NOT NULL,
    imagen           INTEGER,
    modelo           INTEGER,
    -- JSON array como texto. Default '[]' (no '{}' como en Postgres).
    ingredientes     TEXT NOT NULL DEFAULT '[]',
    cardColor        TEXT DEFAULT '#152238',
    cardMessage      TEXT,
    descuento        INTEGER NOT NULL DEFAULT 0 CHECK (descuento >= 0 AND descuento <= 100),
    descuento_inicio TEXT,
    descuento_fin    TEXT,
    FOREIGN KEY (categoria) REFERENCES categorias (id_categ) ON DELETE CASCADE,
    FOREIGN KEY (imagen)    REFERENCES imagenes  (id_image) ON DELETE SET NULL,
    FOREIGN KEY (modelo)    REFERENCES modelos   (id_model) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS historial_colores (
    color   TEXT PRIMARY KEY,
    used_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario                 INTEGER PRIMARY KEY AUTOINCREMENT,
    email                      TEXT NOT NULL UNIQUE,
    password_hash              TEXT NOT NULL,
    puede_crear_platos         INTEGER NOT NULL DEFAULT 0,
    puede_editar_platos        INTEGER NOT NULL DEFAULT 0,
    puede_eliminar_platos      INTEGER NOT NULL DEFAULT 0,
    puede_gestionar_categorias INTEGER NOT NULL DEFAULT 0,
    puede_subir_archivos       INTEGER NOT NULL DEFAULT 0,
    puede_eliminar_archivos    INTEGER NOT NULL DEFAULT 0,
    puede_gestionar_usuarios   INTEGER NOT NULL DEFAULT 0,
    creado_en                  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_platos_categoria      ON platos (categoria);
CREATE INDEX IF NOT EXISTS idx_platos_imagen         ON platos (imagen);
CREATE INDEX IF NOT EXISTS idx_platos_modelo         ON platos (modelo);
CREATE INDEX IF NOT EXISTS idx_platos_descuento_fin  ON platos (descuento_fin);
CREATE INDEX IF NOT EXISTS idx_historial_used_at     ON historial_colores (used_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios (lower(email));
